#!/usr/bin/env python3
import argparse
import datetime
import csv

fieldnames_in = [
        'date',
        'type',
        'amount',
        'tag',
        'description',
        'receipt',
        'creation_date',
        'modification_date'
]
fieldnames_out = [
        'date',
        'payment',  # "Zahlung" in HomeBank
        'info',
        'payee',
        'memo',
        'amount',
        'category',
        'tags'
]

parser = argparse.ArgumentParser(
        description='convert expenseregister cvs file for homebank')
parser.add_argument('expenses_csv')
args = parser.parse_args()

with open(args.expenses_csv, 'r', encoding='utf-8') as csvfile, \
         open('homebank.csv', 'w') as homebank_csvfile:
    reader = csv.DictReader(csvfile, fieldnames=fieldnames_in,
                            delimiter=';', quotechar='"')
    writer = csv.DictWriter(homebank_csvfile, fieldnames=fieldnames_out,
                            delimiter=';', quotechar='"')
    for row in reader:
        if row['date'] == 'sep=' or row['date'] == 'date':
            continue
        if row['amount'] == '.00':
            if row['tag'] != '' or row['description'] != '':
                print('skipping: {} ({})'.format(
                    row['description'], row['tag']))
            continue

        date = datetime.datetime.strptime(row['date'], '%m/%d/%y').strftime('%d.%m.%Y')
        tags = row['tag'].replace(',', ' ')

        outrow = {
                'date':    date,
                'payment': 0,  # FIXME
                'payee':   '',
                'memo':    row['description'],
                'amount':  row['type'] + row['amount'],
                'tags': tags
        }
        writer.writerow(outrow)
